### PR TITLE
[shop] swap fast with noclip

### PR DESCRIPTION
**Pull request by ThomasMonroe314**

### CODE REVIEW

**Comment by ThomasMonroe314** [comment]
please try this and see if it works
@cessna151

**Comment by cessna151** [comment]
This causes the formspec to not allow coins to be placed in the noclip slot. 
:large_orange_diamond:

**Comment by ThomasMonroe314** [comment]
dig and re-place the shop

**Comment by cessna151** [comment]
Ah that does it. Fix #6 
:large_orange_diamond:

**Pull request merged**
